services:
  synthetic-minds:
    image: ghcr.io/satyamhq/synthetic-minds:latest
    container_name: synthetic-minds
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5001
    env_file:
      - .env
    ports:
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads